### ISSUE TITLE
Would it (should it) work as-is for this problem?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [xiaodaigh/SortingLab.jl#22]
https://discourse.julialang.org/t/fast-permutation-vector-code-needed/96357

**Comment by xiaodaigh** [comment]
maybe

**Comment by PetrKryslUCSD** [comment]
Oh, wow. Thank you for the informative and exhaustive answer that shows how much thought you gave this problem.

**Comment by xiaodaigh** [comment]
thanks. it's not clear what the problem is given there's no example input and output. but i posted an answer in the discourse instead of here. have a good day

**Comment by PetrKryslUCSD** [comment]
Sorry, did not see the discourse post at first. :-)
